version: '3'
services:
  api:
    build:
      context: ./api
    command: ['/bin/sh', '-c', 'npm install --quiet && node ./app.js']
    volumes:
      - ./api:/usr/app/
      - /api/usr/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - custom-network
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/app/
      - /frontend/usr/app/node_modules
    command: ['/bin/sh', '-c', 'yarn --quiet && yarn dev']
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    networks:
      - custom-network
networks:
  custom-network:
    external: true